### An Array of Matrix Factorization Methods ...pun intended 

Note the general syntax and operations of matrix objects within numpy

In [64]:
import numpy as np
from scipy import linalg

For now assume our matrices sit within the Real Field

In [66]:
a = np.random.randn(4, 4) 
b=np.random.randn(4, 4) 
a

array([[-0.21044735, -0.92371139, -1.27360204, -0.8644405 ],
       [ 0.55066971, -1.1323387 ,  0.65009368, -0.30442672],
       [ 0.42983165, -0.91662871,  0.28708079,  0.19243045],
       [-1.30095948, -0.48853637,  2.08917593,  1.35074998]])

In [67]:
x=np.random.randn(4)
x

array([-0.80711508, -1.22009422,  0.27195929,  0.47192445])

Taking the dot product, matrix multiplication

In [68]:
np.dot(a,x)

array([0.54255164, 0.97023868, 0.94033671, 2.85170717])

In [69]:
np.matmul(a,b)

array([[ 0.37957211,  1.81886855,  1.07570782, -0.67150488],
       [ 0.58582498,  2.43273673,  0.97314037, -3.79026775],
       [ 0.35943769,  2.69689074,  0.0735202 , -1.87183715],
       [ 0.02045162, -1.20650045, -2.29968539, -2.74103148]])

Compute the Kroneckor $a \otimes b$

- It'd be cool to deep dive on what this really means 

In [70]:
kron=np.kron(a,b)

One of the most well-known matrix factorization methods is the QR factorization where we factor any matrix into a unitary (orthogonal) Q and an upper triangular R

In [71]:
q,r=np.linalg.qr(a)
q,r

(array([[-0.14109133, -0.5264134 , -0.83461378, -0.08001256],
        [ 0.36918839, -0.6071845 ,  0.37747775, -0.59374865],
        [ 0.2881743 , -0.49226742,  0.18505331,  0.80023973],
        [-0.87220912, -0.33449768,  0.3559293 ,  0.02601726]]),
 array([[ 1.49156832, -0.1257616 , -1.31976774, -1.11310869],
        [ 0.        ,  1.7884333 , -0.56443063,  0.09334628],
        [ 0.        ,  0.        ,  2.10508588,  1.12294101],
        [ 0.        ,  0.        ,  0.        ,  0.43905236]]))

We can also explicity access the householder reflections and scalers that generate q and r. Recall that the Householder reflections are a generator for the Unitary group

In [72]:
h,tau=np.linalg.qr(a,mode='raw')
h,tau

(array([[ 1.49156832, -0.32353974, -0.25254271,  0.76436399],
        [-0.1257616 ,  1.7884333 ,  0.35173515, -0.03818496],
        [-1.31976774, -0.56443063,  2.10508588, -0.9383795 ],
        [-1.11310869,  0.09334628,  1.12294101,  0.43905236]]),
 array([1.14109133, 1.77750016, 1.06351521, 0.        ]))

Another useful method for matrix factorization is Singular Value Decomposition or SVD for short.

An interpretation of this method can be classified as unitary diagonalization where for any matrix A we compute the unitary matrices $Q, Q^{-1}$ s.t. $Q^{-1}AQ=S$ where S is a diagonal matrix. Some key points is we know $Q^{-1}$ is the hermitian transpose and does exist as unitary matrices form a group, inverses are well defined. In addition, one can reorder S to be decreasing in magnitude s.t. where all $s_{ii} \geq 0$. The last point arises from the fact any complex number multiplied by their conjugate is positive in magnitude 

In [73]:
q,s,q_inv=np.linalg.svd(a)
q,q_inv

(array([[ 0.42357743, -0.45256062, -0.78442851, -0.02104641],
        [-0.0869646 , -0.72069002,  0.38413557, -0.57051111],
        [-0.08142964, -0.51614982,  0.23179759,  0.820505  ],
        [-0.89799139, -0.09687182, -0.42823084, -0.02908039]]),
 array([[ 0.31940717,  0.07071328, -0.80008686, -0.50283168],
        [-0.21429164,  0.94598322, -0.13085075,  0.20511687],
        [ 0.8968672 ,  0.24852588,  0.36510514,  0.02371385],
        [ 0.21837439, -0.19583226, -0.45764324,  0.83935989]]))

In [74]:
print("Singular Values are", s)

Singular Values are [3.11896521 1.85473032 1.15218578 0.36990331]


The above method underlies a great deal of feature selection models specifically with PCA

Cholesky Decomposition (Special Case of LU factorization for positive definite matrices)
   - Given A to be complex valued and hermitian (conjugate transpose is equivalent) then one can factorize A into a lower triangular L and L-Hermitian (conjugate tranpose/ upper triangular)
   - Holds for reals too as this is just a special case of complex where j=0
   - Unique Cholesky for any symmetric (unitary ) matrix

Generate a positive definite matrix

In [75]:
one=np.ones(4)
pd=[]
for i in range(0,len(one)):
    for j in range(0,len(one)):
        if i<=j:
            pd.append((j+1)**2/(i+1))
        else:
            pd.append(j)
pd=np.array(pd).reshape(len(one),len(one))
pd

array([[ 1.        ,  4.        ,  9.        , 16.        ],
       [ 0.        ,  2.        ,  4.5       ,  8.        ],
       [ 0.        ,  1.        ,  3.        ,  5.33333333],
       [ 0.        ,  1.        ,  2.        ,  4.        ]])

Below is our lower triangular matirx

In [76]:
L=np.linalg.cholesky(pd)
L

array([[1.        , 0.        , 0.        , 0.        ],
       [0.        , 1.41421356, 0.        , 0.        ],
       [0.        , 0.70710678, 1.58113883, 0.        ],
       [0.        , 0.70710678, 0.9486833 , 1.61245155]])

And here is it's hermitian counterpart

In [77]:
L.T

array([[1.        , 0.        , 0.        , 0.        ],
       [0.        , 1.41421356, 0.70710678, 0.70710678],
       [0.        , 0.        , 1.58113883, 0.9486833 ],
       [0.        , 0.        , 0.        , 1.61245155]])

Schur's Factorization

The schur's factorization takes a complex / real block matrix and decomposes it into algebraic operations of its blocks. Specifically given a matrix A schur's method will return $A=LDU$ s.t. L,D,U are block unit lower, diagonal, and unit upper triangular and more notabley L,U are unitary

In scipy's library one can also request the field to output across

In [82]:
Z,T,eigen=linalg.schur(a,sort='lhp')
Z # untiary

array([[-0.45620899,  1.24786391, -1.09238592,  1.0599826 ],
       [-0.90876627, -0.45620899, -0.6640293 ,  0.77808465],
       [ 0.        ,  0.        , -0.88000251, -1.82699731],
       [ 0.        ,  0.        ,  0.        ,  2.0874652 ]])

In [83]:
T

array([[-0.20137195, -0.93924622, -0.14157468, -0.23921222],
       [-0.58352047,  0.29279229, -0.72121695, -0.23156566],
       [-0.61707658, -0.09194882,  0.22127744,  0.74953199],
       [ 0.48802632, -0.15373559, -0.64096725,  0.57215091]])

In [84]:
eigen

3

In [85]:
Z,T,eigen=linalg.schur(a,output='complex',sort='lhp')
Z # untiary

array([[-0.45620899+1.06490217e+00j, -0.16850116+2.94269549e-01j,
         0.02124589+9.35852102e-01j, -0.86766121-3.90370182e-01j],
       [ 0.        +0.00000000e+00j, -0.45620899-1.06490217e+00j,
         0.45857041-7.40057120e-01j,  0.35181404+8.36648588e-01j],
       [ 0.        +0.00000000e+00j,  0.        +0.00000000e+00j,
        -0.88000251+2.45178964e-16j, -0.91819952+1.57950271e+00j],
       [ 0.        +0.00000000e+00j,  0.        +0.00000000e+00j,
         0.        +0.00000000e+00j,  2.0874652 +7.77156117e-16j]])

In [86]:
Z

array([[-0.45620899+1.06490217e+00j, -0.16850116+2.94269549e-01j,
         0.02124589+9.35852102e-01j, -0.86766121-3.90370182e-01j],
       [ 0.        +0.00000000e+00j, -0.45620899-1.06490217e+00j,
         0.45857041-7.40057120e-01j,  0.35181404+8.36648588e-01j],
       [ 0.        +0.00000000e+00j,  0.        +0.00000000e+00j,
        -0.88000251+2.45178964e-16j, -0.91819952+1.57950271e+00j],
       [ 0.        +0.00000000e+00j,  0.        +0.00000000e+00j,
         0.        +0.00000000e+00j,  2.0874652 +7.77156117e-16j]])

In [87]:
T

array([[-0.23450516+0.58327296j, -0.70525733+0.17362663j,
         0.12514497-0.06619763j,  0.00957075-0.23902069j],
       [ 0.47080145+0.10717746j,  0.0478811 -0.43679497j,
         0.63751989-0.33722735j,  0.00926482-0.23138024j],
       [ 0.34463163+0.3242216j , -0.22799178-0.33670051j,
        -0.19559825+0.10346513j, -0.02998838+0.74893184j],
       [-0.35897432-0.13749838j,  0.0231907 +0.33689486j,
         0.56658314-0.29970411j, -0.02289146+0.57169279j]])